const r = {
	"error": false,
	"warning": false,
	"result": {
			"rawData": [
					{
							"DishCategory": null,
							"DishCode": "00268",
							"DishDiscountSumInt": 34,
							"DishName": "Others / Otevrena cena",
							"GuestNum": 1,
							"OrderItems": 5,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": null,
							"DishCode": "00537",
							"DishDiscountSumInt": null,
							"DishName": "- Mayonnaise",
							"GuestNum": 1,
							"OrderItems": 3,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": null,
							"DishCode": "00653",
							"DishDiscountSumInt": null,
							"DishName": "- S SEBOU / TAKE OUT",
							"GuestNum": 1,
							"OrderItems": 2,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": null,
							"DishCode": "02053",
							"DishDiscountSumInt": -1.4,
							"DishName": "Zaokrouhlení ve prospěch hosta",
							"GuestNum": 1,
							"OrderItems": 4,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": null,
							"DishCode": "02455",
							"DishDiscountSumInt": null,
							"DishName": " - NO",
							"GuestNum": 1,
							"OrderItems": 5,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": null,
							"DishCode": "02475",
							"DishDiscountSumInt": null,
							"DishName": " - NO",
							"GuestNum": 1,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": null,
							"DishCode": "02571",
							"DishDiscountSumInt": null,
							"DishName": "- Mango sauce",
							"GuestNum": 1,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": null,
							"DishCode": "05193",
							"DishDiscountSumInt": null,
							"DishName": " - NO",
							"GuestNum": 1,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": null,
							"DishCode": "05339",
							"DishDiscountSumInt": null,
							"DishName": " - NO",
							"GuestNum": 1,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "BAGELS",
							"DishCode": "05335",
							"DishDiscountSumInt": 20,
							"DishName": "- Bezlepkový bagel / Gluten free CS",
							"GuestNum": 1,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "BAGELS",
							"DishCode": "05401",
							"DishDiscountSumInt": 230,
							"DishName": "Black Panther",
							"GuestNum": 1,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "BAGELS",
							"DishCode": "05402",
							"DishDiscountSumInt": 199,
							"DishName": "Salmon Bagel",
							"GuestNum": 1,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "BAGELS",
							"DishCode": "05403",
							"DishDiscountSumInt": 199,
							"DishName": "Burger bagel",
							"GuestNum": 1,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "BAGELS",
							"DishCode": "05405",
							"DishDiscountSumInt": 159,
							"DishName": "Kebab chicken",
							"GuestNum": 1,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "BAGELS",
							"DishCode": "05406",
							"DishDiscountSumInt": 310,
							"DishName": "Caesar chicken",
							"GuestNum": 1,
							"OrderItems": 2,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "BAGELS",
							"DishCode": "05409",
							"DishDiscountSumInt": 77.5,
							"DishName": "Bacon and cheese",
							"GuestNum": 1,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "BEER",
							"DishCode": "05023",
							"DishDiscountSumInt": 49,
							"DishName": "Plzensky Prazdroj (Draft) 0,5 L",
							"GuestNum": 1,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "BREAKFASTS",
							"DishCode": "01039",
							"DishDiscountSumInt": null,
							"DishName": "-  Čaj zelený / Green tea B",
							"GuestNum": 1,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "BREAKFASTS",
							"DishCode": "01040",
							"DishDiscountSumInt": null,
							"DishName": "- Lungo B",
							"GuestNum": 1,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "BREAKFASTS",
							"DishCode": "01042",
							"DishDiscountSumInt": null,
							"DishName": "-  Čaj čerstvý zázvorový / Ginger tea B",
							"GuestNum": 1,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "BREAKFASTS",
							"DishCode": "02521",
							"DishDiscountSumInt": 199,
							"DishName": "Benedict bagel Breakfast KV",
							"GuestNum": 1,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "BREAKFASTS",
							"DishCode": "05029",
							"DishDiscountSumInt": 195,
							"DishName": "Sausages and Egg Breakfast KV",
							"GuestNum": 1,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "BREAKFASTS",
							"DishCode": "05034",
							"DishDiscountSumInt": 398,
							"DishName": "Avocado Breakfast KV",
							"GuestNum": 1,
							"OrderItems": 2,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "BREAKFASTS",
							"DishCode": "05475",
							"DishDiscountSumInt": null,
							"DishName": "- Double espresso B",
							"GuestNum": 1,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "DESSERTS",
							"DishCode": "05183",
							"DishDiscountSumInt": 95,
							"DishName": "Phistachio Cheesecake",
							"GuestNum": 1,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "DESSERTS",
							"DishCode": "05184",
							"DishDiscountSumInt": 47.5,
							"DishName": "Chocolate cake with raspberries",
							"GuestNum": 1,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "DESSERTS",
							"DishCode": "05185",
							"DishDiscountSumInt": 47.5,
							"DishName": "Carrot cake with nuts",
							"GuestNum": 1,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "EXTRA",
							"DishCode": "01065",
							"DishDiscountSumInt": 10,
							"DishName": "Honey (Bar)",
							"GuestNum": 1,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "EXTRA",
							"DishCode": "02823",
							"DishDiscountSumInt": 78,
							"DishName": "Extra Mini sausages",
							"GuestNum": 1,
							"OrderItems": 2,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "FRESH JUICES",
							"DishCode": "05333",
							"DishDiscountSumInt": 119,
							"DishName": "-  Super Orange 0,34 L CS",
							"GuestNum": 1,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "HOT DRINKS",
							"DishCode": "00411",
							"DishDiscountSumInt": 75,
							"DishName": "Cappuccino",
							"GuestNum": 1,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "HOT DRINKS",
							"DishCode": "00416",
							"DishDiscountSumInt": 75,
							"DishName": "Leaf tea",
							"GuestNum": 1,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "HOT DRINKS",
							"DishCode": "00604",
							"DishDiscountSumInt": null,
							"DishName": "- Earl Grey Black tea",
							"GuestNum": 1,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "HOT DRINKS",
							"DishCode": "02270",
							"DishDiscountSumInt": 59,
							"DishName": "Americano",
							"GuestNum": 1,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "KIDS MENU",
							"DishCode": "05541",
							"DishDiscountSumInt": 59,
							"DishName": "Chicken meatballs (kids)",
							"GuestNum": 1,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "KIDS MENU",
							"DishCode": "05543",
							"DishDiscountSumInt": 69.5,
							"DishName": "Nuggets (kids)",
							"GuestNum": 1,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "KIDS MENU",
							"DishCode": "05545",
							"DishDiscountSumInt": 103.5,
							"DishName": "Fries (kids)",
							"GuestNum": 1,
							"OrderItems": 2,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "LEMONADES",
							"DishCode": "00430",
							"DishDiscountSumInt": null,
							"DishName": "Limonáda / Lemonade 0,4 L",
							"GuestNum": 1,
							"OrderItems": 3,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "LEMONADES",
							"DishCode": "00924",
							"DishDiscountSumInt": 75,
							"DishName": "- Cucumber 0,4 L",
							"GuestNum": 1,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "LEMONADES",
							"DishCode": "05186",
							"DishDiscountSumInt": 190,
							"DishName": "- Mango & Maracuja 0,4 L",
							"GuestNum": 1,
							"OrderItems": 2,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "MENU",
							"DishCode": "05226",
							"DishDiscountSumInt": 302.4,
							"DishName": "Super Combo",
							"GuestNum": 1,
							"OrderItems": 2,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "MICHELIN",
							"DishCode": "05410",
							"DishDiscountSumInt": 230,
							"DishName": "Duck Special",
							"GuestNum": 1,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "SNACKS",
							"DishCode": "00206",
							"DishDiscountSumInt": 85,
							"DishName": "Hranolky / Fries",
							"GuestNum": 1,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "SNACKS",
							"DishCode": "00614",
							"DishDiscountSumInt": 237,
							"DishName": "- Fries for Bagels CS",
							"GuestNum": 1,
							"OrderItems": 3,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "SOUP",
							"DishCode": "00547",
							"DishDiscountSumInt": 97.5,
							"DishName": "Soup of the day",
							"GuestNum": 1,
							"OrderItems": 2,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "SOUP",
							"DishCode": "05260",
							"DishDiscountSumInt": null,
							"DishName": "- Rajská polévka / Tomato soup",
							"GuestNum": 1,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "SOUP",
							"DishCode": "05261",
							"DishDiscountSumInt": null,
							"DishName": "- Polévka batátová / Sweet potato soup",
							"GuestNum": 1,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "SPARKLING WINE",
							"DishCode": "02280",
							"DishDiscountSumInt": 59,
							"DishName": "Prosecco 0,1 L",
							"GuestNum": 1,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "TAKE OUT",
							"DishCode": "02327",
							"DishDiscountSumInt": 2,
							"DishName": "- Obaly (Bagel) / Take out (Bagel)",
							"GuestNum": 1,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "TAKE OUT",
							"DishCode": "02332",
							"DishDiscountSumInt": 5,
							"DishName": "- Obaly (Taska) / Take out (Bag)",
							"GuestNum": 1,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "WATER",
							"DishCode": "03340",
							"DishDiscountSumInt": 45,
							"DishName": "Voda",
							"GuestNum": 1,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": null,
							"DishCode": "00268",
							"DishDiscountSumInt": 140.61,
							"DishName": "Others / Otevrena cena",
							"GuestNum": 1,
							"OrderItems": 14,
							"OrderType": "Dame / Bolt / Wolt",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": null,
							"DishCode": "00538",
							"DishDiscountSumInt": null,
							"DishName": "- Ketchup",
							"GuestNum": 1,
							"OrderItems": 8,
							"OrderType": "Dame / Bolt / Wolt",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": null,
							"DishCode": "00540",
							"DishDiscountSumInt": null,
							"DishName": "- Garlic dip",
							"GuestNum": 1,
							"OrderItems": 1,
							"OrderType": "Dame / Bolt / Wolt",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": null,
							"DishCode": "00653",
							"DishDiscountSumInt": null,
							"DishName": "- S SEBOU / TAKE OUT",
							"GuestNum": 1,
							"OrderItems": 10,
							"OrderType": "Dame / Bolt / Wolt",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": null,
							"DishCode": "02053",
							"DishDiscountSumInt": -2.5,
							"DishName": "Zaokrouhlení ve prospěch hosta",
							"GuestNum": 1,
							"OrderItems": 8,
							"OrderType": "Dame / Bolt / Wolt",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": null,
							"DishCode": "02455",
							"DishDiscountSumInt": null,
							"DishName": " - NO",
							"GuestNum": 1,
							"OrderItems": 3,
							"OrderType": "Dame / Bolt / Wolt",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "BAGELS",
							"DishCode": "05401",
							"DishDiscountSumInt": 318.5,
							"DishName": "Black Panther",
							"GuestNum": 1,
							"OrderItems": 2,
							"OrderType": "Dame / Bolt / Wolt",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "BAGELS",
							"DishCode": "05403",
							"DishDiscountSumInt": 171.2,
							"DishName": "Burger bagel",
							"GuestNum": 1,
							"OrderItems": 1,
							"OrderType": "Dame / Bolt / Wolt",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "BAGELS",
							"DishCode": "05405",
							"DishDiscountSumInt": 139.2,
							"DishName": "Kebab chicken",
							"GuestNum": 1,
							"OrderItems": 1,
							"OrderType": "Dame / Bolt / Wolt",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "BAGELS",
							"DishCode": "05407",
							"DishDiscountSumInt": 136.09,
							"DishName": "Guacamole Vegan Bagel",
							"GuestNum": 1,
							"OrderItems": 1,
							"OrderType": "Dame / Bolt / Wolt",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "BAGELS",
							"DishCode": "05409",
							"DishDiscountSumInt": 136,
							"DishName": "Bacon and cheese",
							"GuestNum": 1,
							"OrderItems": 1,
							"OrderType": "Dame / Bolt / Wolt",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "DESSERTS",
							"DishCode": "05185",
							"DishDiscountSumInt": 88,
							"DishName": "Carrot cake with nuts",
							"GuestNum": 1,
							"OrderItems": 1,
							"OrderType": "Dame / Bolt / Wolt",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "EXTRA",
							"DishCode": "01424",
							"DishDiscountSumInt": 30,
							"DishName": "EXTRA Sauces",
							"GuestNum": 1,
							"OrderItems": 1,
							"OrderType": "Dame / Bolt / Wolt",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "LEMONADES",
							"DishCode": "00430",
							"DishDiscountSumInt": null,
							"DishName": "Limonáda / Lemonade 0,4 L",
							"GuestNum": 1,
							"OrderItems": 1,
							"OrderType": "Dame / Bolt / Wolt",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "LEMONADES",
							"DishCode": "00924",
							"DishDiscountSumInt": 68,
							"DishName": "- Cucumber 0,4 L",
							"GuestNum": 1,
							"OrderItems": 1,
							"OrderType": "Dame / Bolt / Wolt",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "MENU",
							"DishCode": "03210",
							"DishDiscountSumInt": 558.4,
							"DishName": "Bagel Box",
							"GuestNum": 1,
							"OrderItems": 2,
							"OrderType": "Dame / Bolt / Wolt",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "MENU",
							"DishCode": "05226",
							"DishDiscountSumInt": 756.2,
							"DishName": "Super Combo",
							"GuestNum": 1,
							"OrderItems": 3,
							"OrderType": "Dame / Bolt / Wolt",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "MICHELIN",
							"DishCode": "05410",
							"DishDiscountSumInt": 196,
							"DishName": "Duck Special",
							"GuestNum": 1,
							"OrderItems": 1,
							"OrderType": "Dame / Bolt / Wolt",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "SALADS",
							"DishCode": "02714",
							"DishDiscountSumInt": 154,
							"DishName": "Beef salad",
							"GuestNum": 1,
							"OrderItems": 1,
							"OrderType": "Dame / Bolt / Wolt",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "SNACKS",
							"DishCode": "00196",
							"DishDiscountSumInt": 294.5,
							"DishName": "Smažená mozzarella / Deepfried mozzarella",
							"GuestNum": 1,
							"OrderItems": 2,
							"OrderType": "Dame / Bolt / Wolt",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "SNACKS",
							"DishCode": "00544",
							"DishDiscountSumInt": 43.2,
							"DishName": "Bagel chips + dip",
							"GuestNum": 1,
							"OrderItems": 1,
							"OrderType": "Dame / Bolt / Wolt",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "SNACKS",
							"DishCode": "00614",
							"DishDiscountSumInt": 302.6,
							"DishName": "- Fries for Bagels CS",
							"GuestNum": 1,
							"OrderItems": 4,
							"OrderType": "Dame / Bolt / Wolt",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "SNACKS",
							"DishCode": "02744",
							"DishDiscountSumInt": 136,
							"DishName": "Kuřecí nugety / Chicken nuggets",
							"GuestNum": 1,
							"OrderItems": 1,
							"OrderType": "Dame / Bolt / Wolt",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": null,
							"DishCode": "00268",
							"DishDiscountSumInt": 40,
							"DishName": "Others / Otevrena cena",
							"GuestNum": 1,
							"OrderItems": 3,
							"OrderType": "Take away",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": null,
							"DishCode": "02053",
							"DishDiscountSumInt": -0.2,
							"DishName": "Zaokrouhlení ve prospěch hosta",
							"GuestNum": 1,
							"OrderItems": 1,
							"OrderType": "Take away",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "MENU",
							"DishCode": "03210",
							"DishDiscountSumInt": 279.2,
							"DishName": "Bagel Box",
							"GuestNum": 1,
							"OrderItems": 1,
							"OrderType": "Take away",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": null,
							"DishCode": "00538",
							"DishDiscountSumInt": null,
							"DishName": "- Ketchup",
							"GuestNum": 2,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": null,
							"DishCode": "00540",
							"DishDiscountSumInt": null,
							"DishName": "- Garlic dip",
							"GuestNum": 2,
							"OrderItems": 6,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": null,
							"DishCode": "02053",
							"DishDiscountSumInt": -0.7,
							"DishName": "Zaokrouhlení ve prospěch hosta",
							"GuestNum": 2,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": null,
							"DishCode": "02455",
							"DishDiscountSumInt": null,
							"DishName": " - NO",
							"GuestNum": 2,
							"OrderItems": 2,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": null,
							"DishCode": "05193",
							"DishDiscountSumInt": null,
							"DishName": " - NO",
							"GuestNum": 2,
							"OrderItems": 2,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": null,
							"DishCode": "05339",
							"DishDiscountSumInt": null,
							"DishName": " - NO",
							"GuestNum": 2,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "BAGELS",
							"DishCode": "05332",
							"DishDiscountSumInt": 17,
							"DishName": "- Bezlepkový bagel / Gluten free CS",
							"GuestNum": 2,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "BAGELS",
							"DishCode": "05404",
							"DishDiscountSumInt": 370,
							"DishName": "Beef in Brooklyn",
							"GuestNum": 2,
							"OrderItems": 2,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "BREAKFASTS",
							"DishCode": "00624",
							"DishDiscountSumInt": null,
							"DishName": "- Latte B",
							"GuestNum": 2,
							"OrderItems": 2,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "BREAKFASTS",
							"DishCode": "01042",
							"DishDiscountSumInt": null,
							"DishName": "-  Čaj čerstvý zázvorový / Ginger tea B",
							"GuestNum": 2,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "BREAKFASTS",
							"DishCode": "02521",
							"DishDiscountSumInt": 199,
							"DishName": "Benedict bagel Breakfast KV",
							"GuestNum": 2,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "BREAKFASTS",
							"DishCode": "02797",
							"DishDiscountSumInt": 526.5,
							"DishName": "Breakfast with bagel KV",
							"GuestNum": 2,
							"OrderItems": 3,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "BREAKFASTS",
							"DishCode": "05029",
							"DishDiscountSumInt": 195,
							"DishName": "Sausages and Egg Breakfast KV",
							"GuestNum": 2,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "BREAKFASTS",
							"DishCode": "05041",
							"DishDiscountSumInt": 155,
							"DishName": "Scramble Breakfast KV",
							"GuestNum": 2,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "BREAKFASTS",
							"DishCode": "05179",
							"DishDiscountSumInt": 199,
							"DishName": "Potato pancakes KV",
							"GuestNum": 2,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "BREAKFASTS",
							"DishCode": "05438",
							"DishDiscountSumInt": null,
							"DishName": "- Flat white B",
							"GuestNum": 2,
							"OrderItems": 6,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "BREAKFASTS",
							"DishCode": "05500",
							"DishDiscountSumInt": 378,
							"DishName": "Syrniki Breakfast KV",
							"GuestNum": 2,
							"OrderItems": 2,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "DESSERTS",
							"DishCode": "01496",
							"DishDiscountSumInt": 49,
							"DishName": "Chocolate balls",
							"GuestNum": 2,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "DESSERTS",
							"DishCode": "05183",
							"DishDiscountSumInt": 95,
							"DishName": "Phistachio Cheesecake",
							"GuestNum": 2,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "DESSERTS",
							"DishCode": "05430",
							"DishDiscountSumInt": 29,
							"DishName": "Banánový chlebíček / Banana bread",
							"GuestNum": 2,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "EXTRA",
							"DishCode": "05328",
							"DishDiscountSumInt": 15,
							"DishName": "- Slany karamel / Salted caramel CS",
							"GuestNum": 2,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "FRESH JUICES",
							"DishCode": "00418",
							"DishDiscountSumInt": 220.15,
							"DishName": "Super orange 0,34 L",
							"GuestNum": 2,
							"OrderItems": 2,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "HOT DRINKS",
							"DishCode": "00411",
							"DishDiscountSumInt": 75,
							"DishName": "Cappuccino",
							"GuestNum": 2,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "HOT DRINKS",
							"DishCode": "00414",
							"DishDiscountSumInt": 89,
							"DishName": "Ledová káva / Iced coffee",
							"GuestNum": 2,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "LEMONADES",
							"DishCode": "00430",
							"DishDiscountSumInt": null,
							"DishName": "Limonáda / Lemonade 0,4 L",
							"GuestNum": 2,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "LEMONADES",
							"DishCode": "00923",
							"DishDiscountSumInt": 75,
							"DishName": "- Raspberry 0,4 L",
							"GuestNum": 2,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "MICHELIN",
							"DishCode": "05410",
							"DishDiscountSumInt": 460,
							"DishName": "Duck Special",
							"GuestNum": 2,
							"OrderItems": 2,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "SALADS",
							"DishCode": "00230",
							"DishDiscountSumInt": 378,
							"DishName": "Bagel Lounge Caesar",
							"GuestNum": 2,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "SMOOTHIES",
							"DishCode": "00423",
							"DishDiscountSumInt": 101.15,
							"DishName": "Berry kiss 0,34 L",
							"GuestNum": 2,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "SNACKS",
							"DishCode": "00196",
							"DishDiscountSumInt": 143.65,
							"DishName": "Smažená mozzarella / Deepfried mozzarella",
							"GuestNum": 2,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "SNACKS",
							"DishCode": "00206",
							"DishDiscountSumInt": 242.25,
							"DishName": "Hranolky / Fries",
							"GuestNum": 2,
							"OrderItems": 3,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "SNACKS",
							"DishCode": "00544",
							"DishDiscountSumInt": 39,
							"DishName": "Bagel chips + dip",
							"GuestNum": 2,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "SNACKS",
							"DishCode": "00614",
							"DishDiscountSumInt": 158,
							"DishName": "- Fries for Bagels CS",
							"GuestNum": 2,
							"OrderItems": 2,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "SOUP",
							"DishCode": "00547",
							"DishDiscountSumInt": 195,
							"DishName": "Soup of the day",
							"GuestNum": 2,
							"OrderItems": 2,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "SOUP",
							"DishCode": "05260",
							"DishDiscountSumInt": null,
							"DishName": "- Rajská polévka / Tomato soup",
							"GuestNum": 2,
							"OrderItems": 2,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "WATER",
							"DishCode": "00593",
							"DishDiscountSumInt": 49,
							"DishName": "Mattoni perliva/Mattoni sparkling 0,33 L",
							"GuestNum": 2,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "WATER",
							"DishCode": "00596",
							"DishDiscountSumInt": 245,
							"DishName": "Mattoni neperliva/Mattoni still 0,33 L",
							"GuestNum": 2,
							"OrderItems": 3,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": null,
							"DishCode": "00538",
							"DishDiscountSumInt": null,
							"DishName": "- Ketchup",
							"GuestNum": 3,
							"OrderItems": 2,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": null,
							"DishCode": "00540",
							"DishDiscountSumInt": null,
							"DishName": "- Garlic dip",
							"GuestNum": 3,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": null,
							"DishCode": "02053",
							"DishDiscountSumInt": -0.8,
							"DishName": "Zaokrouhlení ve prospěch hosta",
							"GuestNum": 3,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": null,
							"DishCode": "02455",
							"DishDiscountSumInt": null,
							"DishName": " - NO",
							"GuestNum": 3,
							"OrderItems": 2,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": null,
							"DishCode": "03013",
							"DishDiscountSumInt": null,
							"DishName": "- Pepsi cola 0,4 L",
							"GuestNum": 3,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "BAGELS",
							"DishCode": "00551",
							"DishDiscountSumInt": null,
							"DishName": "- Bagel Plain",
							"GuestNum": 3,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "BAGELS",
							"DishCode": "02996",
							"DishDiscountSumInt": null,
							"DishName": "- Caesar chicken",
							"GuestNum": 3,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "BAGELS",
							"DishCode": "05332",
							"DishDiscountSumInt": 20,
							"DishName": "- Bezlepkový bagel / Gluten free CS",
							"GuestNum": 3,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "BAGELS",
							"DishCode": "05401",
							"DishDiscountSumInt": 586.5,
							"DishName": "Black Panther",
							"GuestNum": 3,
							"OrderItems": 3,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "BREAKFASTS",
							"DishCode": "01037",
							"DishDiscountSumInt": null,
							"DishName": "-  Čaj Assam / Assam tea B",
							"GuestNum": 3,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "BREAKFASTS",
							"DishCode": "02521",
							"DishDiscountSumInt": 199,
							"DishName": "Benedict bagel Breakfast KV",
							"GuestNum": 3,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "BREAKFASTS",
							"DishCode": "05029",
							"DishDiscountSumInt": 195,
							"DishName": "Sausages and Egg Breakfast KV",
							"GuestNum": 3,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "BREAKFASTS",
							"DishCode": "05034",
							"DishDiscountSumInt": 199,
							"DishName": "Avocado Breakfast KV",
							"GuestNum": 3,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "BREAKFASTS",
							"DishCode": "05438",
							"DishDiscountSumInt": null,
							"DishName": "- Flat white B",
							"GuestNum": 3,
							"OrderItems": 3,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "BREAKFASTS",
							"DishCode": "05475",
							"DishDiscountSumInt": null,
							"DishName": "- Double espresso B",
							"GuestNum": 3,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "BREAKFASTS",
							"DishCode": "05500",
							"DishDiscountSumInt": 567,
							"DishName": "Syrniki Breakfast KV",
							"GuestNum": 3,
							"OrderItems": 2,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "EXTRA",
							"DishCode": "02349",
							"DishDiscountSumInt": 35,
							"DishName": "Dětské jablečné šťávy / Kids apple juice",
							"GuestNum": 3,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "EXTRA",
							"DishCode": "02465",
							"DishDiscountSumInt": 39,
							"DishName": "- Extra Sausages 70 gr CS",
							"GuestNum": 3,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "KIDS MENU",
							"DishCode": "05524",
							"DishDiscountSumInt": 59,
							"DishName": "Scrambled (kids)",
							"GuestNum": 3,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "LEMONADES",
							"DishCode": "00430",
							"DishDiscountSumInt": null,
							"DishName": "Limonáda / Lemonade 0,4 L",
							"GuestNum": 3,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "LEMONADES",
							"DishCode": "00924",
							"DishDiscountSumInt": 127.5,
							"DishName": "- Cucumber 0,4 L",
							"GuestNum": 3,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "MENU",
							"DishCode": "03211",
							"DishDiscountSumInt": null,
							"DishName": "- Bacon and cheese ",
							"GuestNum": 3,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "MENU",
							"DishCode": "03326",
							"DishDiscountSumInt": 299,
							"DishName": "Slevomat Bagel Box",
							"GuestNum": 3,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "SNACKS",
							"DishCode": "00614",
							"DishDiscountSumInt": 67.15,
							"DishName": "- Fries for Bagels CS",
							"GuestNum": 3,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "SNACKS",
							"DishCode": "01557",
							"DishDiscountSumInt": null,
							"DishName": "- Fries",
							"GuestNum": 3,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "SNACKS",
							"DishCode": "05517",
							"DishDiscountSumInt": 126.65,
							"DishName": "COMBO Smažená mozzarella / Deepfried mozzarella",
							"GuestNum": 3,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": null,
							"DishCode": "00538",
							"DishDiscountSumInt": null,
							"DishName": "- Ketchup",
							"GuestNum": 4,
							"OrderItems": 2,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "BAGELS",
							"DishCode": "05404",
							"DishDiscountSumInt": 185,
							"DishName": "Beef in Brooklyn",
							"GuestNum": 4,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "EXTRA",
							"DishCode": "01424",
							"DishDiscountSumInt": 15,
							"DishName": "EXTRA Sauces",
							"GuestNum": 4,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "KIDS MENU",
							"DishCode": "05545",
							"DishDiscountSumInt": 138,
							"DishName": "Fries (kids)",
							"GuestNum": 4,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "LEMONADES",
							"DishCode": "00430",
							"DishDiscountSumInt": null,
							"DishName": "Limonáda / Lemonade 0,4 L",
							"GuestNum": 4,
							"OrderItems": 2,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "LEMONADES",
							"DishCode": "00923",
							"DishDiscountSumInt": 150,
							"DishName": "- Raspberry 0,4 L",
							"GuestNum": 4,
							"OrderItems": 2,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					},
					{
							"DishCategory": "SNACKS",
							"DishCode": "00614",
							"DishDiscountSumInt": 79,
							"DishName": "- Fries for Bagels CS",
							"GuestNum": 4,
							"OrderItems": 1,
							"OrderType": "Běžná objednávka",
							"_BusinessDays": 1,
							"_SalesNet": 14139.01
					}
			],
			"totalDaysInPeriod": 1,
			"totalRevenueInPeriod": 14139.01,
			"totalMainItemSalesNet": 0,
			"totalMainItemCost": 0,
			"totalMainItemSalesGross": 0,
			"totalMainItemQty": 0
	},
	"formValidationError": false
}

const newR = r.result.rawData.filter((item) => item.DishCategory === "DESSERTS");
const s = newR.reduce((sum, item) => sum + item.OrderItems, 0);
const v = newR.map(item => [item.DishName, item.OrderItems]);
const l = r.result.rawData.length;

console.log(s, v, l);