const r = {
  error: false,
  warning: false,
  result: {
    rawData: [
      {
        CashRegisterName: "Kasa (101)",
        DishDiscountSumInt: 227,
        GuestNum: 1,
        OrderNum: 2,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 13890.83,
      },
      {
        CashRegisterName: "Kasa (101)",
        DishDiscountSumInt: 808,
        GuestNum: 1,
        OrderNum: 12,
        OrderType: "Dame / Bolt / Wolt",
        _BusinessDays: 1,
        _SalesNet: 13890.83,
      },
      {
        CashRegisterName: "Kasa (101)",
        DishDiscountSumInt: 199,
        GuestNum: 1,
        OrderNum: 14,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 13890.83,
      },
      {
        CashRegisterName: "Kasa (101)",
        DishDiscountSumInt: 295,
        GuestNum: 1,
        OrderNum: 16,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 13890.83,
      },
      {
        CashRegisterName: "Kasa (101)",
        DishDiscountSumInt: 634,
        GuestNum: 1,
        OrderNum: 21,
        OrderType: "Dame / Bolt / Wolt",
        _BusinessDays: 1,
        _SalesNet: 13890.83,
      },
      {
        CashRegisterName: "Kasa (101)",
        DishDiscountSumInt: 114,
        GuestNum: 1,
        OrderNum: 22,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 13890.83,
      },
      {
        CashRegisterName: "Kasa (101)",
        DishDiscountSumInt: 438,
        GuestNum: 1,
        OrderNum: 24,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 13890.83,
      },
      {
        CashRegisterName: "Kasa (101)",
        DishDiscountSumInt: 642,
        GuestNum: 1,
        OrderNum: 25,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 13890.83,
      },
      {
        CashRegisterName: "Kasa (101)",
        DishDiscountSumInt: 831,
        GuestNum: 1,
        OrderNum: 27,
        OrderType: "Dame / Bolt / Wolt",
        _BusinessDays: 1,
        _SalesNet: 13890.83,
      },
      {
        CashRegisterName: "Kasa (101)",
        DishDiscountSumInt: 371,
        GuestNum: 1,
        OrderNum: 28,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 13890.83,
      },
      {
        CashRegisterName: "Kasa (101)",
        DishDiscountSumInt: 119,
        GuestNum: 1,
        OrderNum: 29,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 13890.83,
      },
      {
        CashRegisterName: "Kasa (101)",
        DishDiscountSumInt: 195,
        GuestNum: 1,
        OrderNum: 30,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 13890.83,
      },
      {
        CashRegisterName: "Kasa (101)",
        DishDiscountSumInt: 574,
        GuestNum: 1,
        OrderNum: 32,
        OrderType: "Dame / Bolt / Wolt",
        _BusinessDays: 1,
        _SalesNet: 13890.83,
      },
      {
        CashRegisterName: "Kasa (101)",
        DishDiscountSumInt: 319,
        GuestNum: 1,
        OrderNum: 34,
        OrderType: "Dame / Bolt / Wolt",
        _BusinessDays: 1,
        _SalesNet: 13890.83,
      },
      {
        CashRegisterName: "Kasa (101)",
        DishDiscountSumInt: 234,
        GuestNum: 1,
        OrderNum: 38,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 13890.83,
      },
      {
        CashRegisterName: "Kasa (101)",
        DishDiscountSumInt: 394,
        GuestNum: 2,
        OrderNum: 1,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 13890.83,
      },
      {
        CashRegisterName: "Kasa (101)",
        DishDiscountSumInt: 394,
        GuestNum: 2,
        OrderNum: 5,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 13890.83,
      },
      {
        CashRegisterName: "Kasa (101)",
        DishDiscountSumInt: 684,
        GuestNum: 2,
        OrderNum: 9,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 13890.83,
      },
      {
        CashRegisterName: "Kasa (101)",
        DishDiscountSumInt: 568,
        GuestNum: 2,
        OrderNum: 10,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 13890.83,
      },
      {
        CashRegisterName: "Kasa (101)",
        DishDiscountSumInt: 583,
        GuestNum: 2,
        OrderNum: 11,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 13890.83,
      },
      {
        CashRegisterName: "Kasa (101)",
        DishDiscountSumInt: 558,
        GuestNum: 2,
        OrderNum: 15,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 13890.83,
      },
      {
        CashRegisterName: "Kasa (101)",
        DishDiscountSumInt: 373,
        GuestNum: 2,
        OrderNum: 20,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 13890.83,
      },
      {
        CashRegisterName: "Kasa (101)",
        DishDiscountSumInt: 544,
        GuestNum: 2,
        OrderNum: 23,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 13890.83,
      },
      {
        CashRegisterName: "Kasa (101)",
        DishDiscountSumInt: 727,
        GuestNum: 3,
        OrderNum: 4,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 13890.83,
      },
      {
        CashRegisterName: "Kasa (101)",
        DishDiscountSumInt: 835,
        GuestNum: 3,
        OrderNum: 7,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 13890.83,
      },
      {
        CashRegisterName: "Kasa (101)",
        DishDiscountSumInt: 877,
        GuestNum: 3,
        OrderNum: 13,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 13890.83,
      },
      {
        CashRegisterName: "Kasa (101)",
        DishDiscountSumInt: 779,
        GuestNum: 4,
        OrderNum: 18,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 13890.83,
      },
      {
        CashRegisterName: "Kasa (101)",
        DishDiscountSumInt: 1079,
        GuestNum: 5,
        OrderNum: 8,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 13890.83,
      },
      {
        CashRegisterName: "Kasa (101)",
        DishDiscountSumInt: 1377,
        GuestNum: 6,
        OrderNum: 19,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 13890.83,
      },
    ],
    totalDaysInPeriod: 1,
    totalRevenueInPeriod: 13890.83,
    totalMainItemSalesNet: 0,
    totalMainItemCost: 0,
    totalMainItemSalesGross: 0,
    totalMainItemQty: 0,
  },
  formValidationError: false,
};

const newR = r.result.rawData.filter(
  (item) => item.DishCategory === "DESSERTS"
);
const s = newR.reduce((sum, item) => sum + item.OrderItems, 0);
const v = newR.map((item) => [item.DishName, item.OrderItems]);
const l = r.result.rawData.length;

console.log(
  r.result.rawData.filter((item) => item.OrderType === "Dame / Bolt / Wolt")
    .length
);
