const r = {
  error: false,
  warning: false,
  result: {
    rawData: [
      {
        DishCategory: null,
        DishDiscountSumInt: null,
        GuestNum: 1,
        OrderItems: 24,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: "BAGELS",
        DishDiscountSumInt: 1326,
        GuestNum: 1,
        OrderItems: 11,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: "BEER",
        DishDiscountSumInt: 147,
        GuestNum: 1,
        OrderItems: 1,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: "BREAKFASTS",
        DishDiscountSumInt: 1890,
        GuestNum: 1,
        OrderItems: 20,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: "DESSERTS",
        DishDiscountSumInt: 260,
        GuestNum: 1,
        OrderItems: 2,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: "EXTRA",
        DishDiscountSumInt: 215,
        GuestNum: 1,
        OrderItems: 6,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: "FRESH JUICES",
        DishDiscountSumInt: 119,
        GuestNum: 1,
        OrderItems: 1,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: "HOT DRINKS",
        DishDiscountSumInt: 454,
        GuestNum: 1,
        OrderItems: 5,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: "KIDS MENU",
        DishDiscountSumInt: 69,
        GuestNum: 1,
        OrderItems: 1,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: "LEMONADES",
        DishDiscountSumInt: 95,
        GuestNum: 1,
        OrderItems: 2,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: "MENU",
        DishDiscountSumInt: 299,
        GuestNum: 1,
        OrderItems: 2,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: "MICHELIN",
        DishDiscountSumInt: 230,
        GuestNum: 1,
        OrderItems: 1,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: "SALADS",
        DishDiscountSumInt: 378,
        GuestNum: 1,
        OrderItems: 2,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: "SNACKS",
        DishDiscountSumInt: 158,
        GuestNum: 1,
        OrderItems: 3,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: "SPARKLING N/A DRINKS",
        DishDiscountSumInt: 49,
        GuestNum: 1,
        OrderItems: 1,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: "SPARKLING WINE",
        DishDiscountSumInt: 59,
        GuestNum: 1,
        OrderItems: 1,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: "TAKE OUT",
        DishDiscountSumInt: 16,
        GuestNum: 1,
        OrderItems: 5,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: "WATER",
        DishDiscountSumInt: 84,
        GuestNum: 1,
        OrderItems: 2,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: null,
        DishDiscountSumInt: 181.48,
        GuestNum: 1,
        OrderItems: 50,
        OrderType: "Dame / Bolt / Wolt",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: "BAGELS",
        DishDiscountSumInt: 1539.38,
        GuestNum: 1,
        OrderItems: 12,
        OrderType: "Dame / Bolt / Wolt",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: "BREAKFASTS",
        DishDiscountSumInt: 1011.98,
        GuestNum: 1,
        OrderItems: 9,
        OrderType: "Dame / Bolt / Wolt",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: "LEMONADES",
        DishDiscountSumInt: 68,
        GuestNum: 1,
        OrderItems: 2,
        OrderType: "Dame / Bolt / Wolt",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: "MENU",
        DishDiscountSumInt: 1904.27,
        GuestNum: 1,
        OrderItems: 8,
        OrderType: "Dame / Bolt / Wolt",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: "MICHELIN",
        DishDiscountSumInt: 401.16,
        GuestNum: 1,
        OrderItems: 2,
        OrderType: "Dame / Bolt / Wolt",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: "SNACKS",
        DishDiscountSumInt: 915.88,
        GuestNum: 1,
        OrderItems: 9,
        OrderType: "Dame / Bolt / Wolt",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: "TAKE OUT",
        DishDiscountSumInt: 50.85,
        GuestNum: 1,
        OrderItems: 9,
        OrderType: "Dame / Bolt / Wolt",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: null,
        DishDiscountSumInt: -0.6,
        GuestNum: 2,
        OrderItems: 53,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: "BAGELS",
        DishDiscountSumInt: 3923.36,
        GuestNum: 2,
        OrderItems: 24,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: "BEER",
        DishDiscountSumInt: 303,
        GuestNum: 2,
        OrderItems: 6,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: "BREAKFASTS",
        DishDiscountSumInt: 2547,
        GuestNum: 2,
        OrderItems: 24,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: "DESSERTS",
        DishDiscountSumInt: 838.27,
        GuestNum: 2,
        OrderItems: 9,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: "EXTRA",
        DishDiscountSumInt: 103,
        GuestNum: 2,
        OrderItems: 4,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: "FRESH JUICES",
        DishDiscountSumInt: 357,
        GuestNum: 2,
        OrderItems: 2,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: "HOT DRINKS",
        DishDiscountSumInt: 582.1,
        GuestNum: 2,
        OrderItems: 8,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: "KIDS MENU",
        DishDiscountSumInt: 148,
        GuestNum: 2,
        OrderItems: 3,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: "LEMONADES",
        DishDiscountSumInt: 1441.8,
        GuestNum: 2,
        OrderItems: 34,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: "MENU",
        DishDiscountSumInt: 299,
        GuestNum: 2,
        OrderItems: 2,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: "MICHELIN",
        DishDiscountSumInt: 1150,
        GuestNum: 2,
        OrderItems: 4,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: "SALADS",
        DishDiscountSumInt: 572,
        GuestNum: 2,
        OrderItems: 4,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: "SNACKS",
        DishDiscountSumInt: 2954.29,
        GuestNum: 2,
        OrderItems: 24,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: "SOUP",
        DishDiscountSumInt: 65,
        GuestNum: 2,
        OrderItems: 2,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: "SPARKLING N/A DRINKS",
        DishDiscountSumInt: 196,
        GuestNum: 2,
        OrderItems: 2,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: "SPARKLING WINE",
        DishDiscountSumInt: 215.22,
        GuestNum: 2,
        OrderItems: 2,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: "TAKE OUT",
        DishDiscountSumInt: 4.56,
        GuestNum: 2,
        OrderItems: 1,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: "WATER",
        DishDiscountSumInt: 378,
        GuestNum: 2,
        OrderItems: 8,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: null,
        DishDiscountSumInt: null,
        GuestNum: 2,
        OrderItems: 4,
        OrderType: "Dame / Bolt / Wolt",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: "BAGELS",
        DishDiscountSumInt: null,
        GuestNum: 2,
        OrderItems: 4,
        OrderType: "Dame / Bolt / Wolt",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: "MENU",
        DishDiscountSumInt: 598,
        GuestNum: 2,
        OrderItems: 4,
        OrderType: "Dame / Bolt / Wolt",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: "SNACKS",
        DishDiscountSumInt: null,
        GuestNum: 2,
        OrderItems: 2,
        OrderType: "Dame / Bolt / Wolt",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: null,
        DishDiscountSumInt: null,
        GuestNum: 3,
        OrderItems: 7,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: "BAGELS",
        DishDiscountSumInt: 857,
        GuestNum: 3,
        OrderItems: 4,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: "BEER",
        DishDiscountSumInt: 167,
        GuestNum: 3,
        OrderItems: 3,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: "BREAKFASTS",
        DishDiscountSumInt: 1130,
        GuestNum: 3,
        OrderItems: 12,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: "HOT DRINKS",
        DishDiscountSumInt: 164,
        GuestNum: 3,
        OrderItems: 2,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: "LEMONADES",
        DishDiscountSumInt: 95,
        GuestNum: 3,
        OrderItems: 2,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: "MICHELIN",
        DishDiscountSumInt: 230,
        GuestNum: 3,
        OrderItems: 1,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: "WATER",
        DishDiscountSumInt: 49,
        GuestNum: 3,
        OrderItems: 1,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: null,
        DishDiscountSumInt: 37.35,
        GuestNum: 4,
        OrderItems: 28,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: "BAGELS",
        DishDiscountSumInt: 1170.5,
        GuestNum: 4,
        OrderItems: 7,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: "BEER",
        DishDiscountSumInt: 41.65,
        GuestNum: 4,
        OrderItems: 1,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: "BREAKFASTS",
        DishDiscountSumInt: 189,
        GuestNum: 4,
        OrderItems: 2,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: "COCKTAILS",
        DishDiscountSumInt: 119,
        GuestNum: 4,
        OrderItems: 1,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: "DESSERTS",
        DishDiscountSumInt: 506,
        GuestNum: 4,
        OrderItems: 5,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: "EXTRA",
        DishDiscountSumInt: 15,
        GuestNum: 4,
        OrderItems: 2,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: "HOT DRINKS",
        DishDiscountSumInt: 513.75,
        GuestNum: 4,
        OrderItems: 6,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: "KIDS MENU",
        DishDiscountSumInt: 198,
        GuestNum: 4,
        OrderItems: 2,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: "LEMONADES",
        DishDiscountSumInt: 415,
        GuestNum: 4,
        OrderItems: 6,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: "MICHELIN",
        DishDiscountSumInt: 586.5,
        GuestNum: 4,
        OrderItems: 3,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: "SALADS",
        DishDiscountSumInt: 318,
        GuestNum: 4,
        OrderItems: 1,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: "SMOOTHIES",
        DishDiscountSumInt: 202.3,
        GuestNum: 4,
        OrderItems: 1,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: "SNACKS",
        DishDiscountSumInt: 803.3,
        GuestNum: 4,
        OrderItems: 8,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: "SPARKLING WINE",
        DishDiscountSumInt: 118,
        GuestNum: 4,
        OrderItems: 1,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: "WATER",
        DishDiscountSumInt: 188.65,
        GuestNum: 4,
        OrderItems: 2,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: null,
        DishDiscountSumInt: null,
        GuestNum: 5,
        OrderItems: 1,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: "BAGELS",
        DishDiscountSumInt: 199,
        GuestNum: 5,
        OrderItems: 1,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: "BREAKFASTS",
        DishDiscountSumInt: 549,
        GuestNum: 5,
        OrderItems: 6,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: "EXTRA",
        DishDiscountSumInt: 74,
        GuestNum: 5,
        OrderItems: 2,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: "SPARKLING N/A DRINKS",
        DishDiscountSumInt: 49,
        GuestNum: 5,
        OrderItems: 1,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: null,
        DishDiscountSumInt: null,
        GuestNum: 7,
        OrderItems: 8,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: "BAGELS",
        DishDiscountSumInt: 1366,
        GuestNum: 7,
        OrderItems: 7,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: "FRESH JUICES",
        DishDiscountSumInt: 119,
        GuestNum: 7,
        OrderItems: 1,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: "HOT DRINKS",
        DishDiscountSumInt: 75,
        GuestNum: 7,
        OrderItems: 1,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: "LEMONADES",
        DishDiscountSumInt: 380,
        GuestNum: 7,
        OrderItems: 2,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
      {
        DishCategory: "SNACKS",
        DishDiscountSumInt: 474,
        GuestNum: 7,
        OrderItems: 6,
        OrderType: "Běžná objednávka",
        _BusinessDays: 1,
        _SalesNet: 35203.37,
      },
    ],
    totalDaysInPeriod: 1,
    totalRevenueInPeriod: 13890.83,
    totalMainItemSalesNet: 0,
    totalMainItemCost: 0,
    totalMainItemSalesGross: 0,
    totalMainItemQty: 0,
  },
  formValidationError: false,
};

const newR = r.result.rawData.filter((item) => item.DishCategory === "SNACKS");
const del = r.result.rawData.filter(
  (item) => item.OrderType === "Běžná objednávka"
);
const s = newR.reduce((sum, item) => sum + item.OrderItems, 0);
const v = newR.map((item) => [item.DishName, item.OrderItems]);
const l = r.result.rawData.length;

function sumIndicesByItemName(items) {
  // Create an object to hold the summed indices for each item
  const summedIndices = {};

  // Iterate through each item in the array
  items.forEach((item) => {
    const name = item[0]; // Item name is the first element
    const index = item[1]; // Index to sum is the second element

    // If the item name already exists in the object, add to its sum
    // Otherwise, initialize it with the current index
    if (summedIndices.hasOwnProperty(name)) {
      summedIndices[name] += index;
    } else {
      summedIndices[name] = index;
    }
  });

  // If you need the result as an array of arrays [[itemName, sumIndex], ...]
  const resultArray = Object.entries(summedIndices);

  // Return the result
  return resultArray;
}

console.log(del.length);
